# 服务名称
name="dcron"

# 对外服务端口
port=7777

# 数据存储目录，空值时为系统默认目录
# storage=""

# etcd 用于服务发现、管理，若不配置则服务为单机版，不支持集群特性
# etcd 服务结点：[ip1:port,ip2:port[,...]]
etcd_endpoints = ["127.0.0.1:2379","127.0.0.1:2379","127.0.0.1:2379"]