# 服务名称，注册 etcd 后，所有服务数据都在 name 空间下
name="dcron"

# dcron 对外服务端口
port=7777

# 数据存储目录，空值时为系统默认目录
storage=""

# etcd 服务结点：[ip1:port,ip2:port[,...]]
etcd_endpoints = ["127.0.0.1:2379","127.0.0.1:2379","127.0.0.1:2379"]